# Generated by Django 5.2.4 on 2025-07-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.ImageField(upload_to='Damage')),
                ('is_condition', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.ImageField(upload_to='Expeditions')),
            ],
        ),
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.ImageField(upload_to='Loot')),
            ],
            options={
                'verbose_name': 'Loot',
                'verbose_name_plural': 'Loot',
            },
        ),
        migrations.CreateModel(
            name='Nightfarer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('summary', models.ImageField(upload_to='Nightfarers')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('min_level', models.PositiveSmallIntegerField(default=2)),
                ('recommended_level', models.PositiveSmallIntegerField(default=8)),
                ('image', models.ImageField(upload_to='Locations')),
                ('contains', models.ManyToManyField(blank=True, to='cheatsheet.loot')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_shifting_earth', models.BooleanField(default=False)),
                ('rewards', models.ManyToManyField(blank=True, to='cheatsheet.loot')),
            ],
        ),
        migrations.CreateModel(
            name='Nightlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expedition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Nightlords', to='cheatsheet.expedition')),
                ('main_weakness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheatsheet.damage')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet.damage')),
                ('nightlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='cheatsheet.nightlord')),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='Walkthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Walkthrough')),
                ('parent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('step', 'parent_event'), name='unique_walkthrough_step')],
            },
        ),
    ]
