# Generated by Django 5.2.4 on 2025-07-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.ImageField(upload_to='Damage')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('min_level', models.PositiveSmallIntegerField(default=2)),
                ('image', models.ImageField(upload_to='Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Nightfarer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('summary', models.ImageField(upload_to='Nightfarers')),
            ],
        ),
        migrations.CreateModel(
            name='Nightlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.ImageField(upload_to='Nightlords')),
                ('main_weakness', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cheatsheet.damage')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.SmallIntegerField(default=0)),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheatsheet.damage')),
                ('nightlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='cheatsheet.nightlord')),
            ],
        ),
    ]
