# Generated by Django 5.2.4 on 2025-07-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightlord',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
