# Generated by Django 5.2.4 on 2025-07-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheet', '0002_nightlord_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightlord',
            name='display_order',
        ),
        migrations.AddField(
            model_name='expedition',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
