# Generated by Django 5.2.4 on 2025-07-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheet', '0004_remove_location_min_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
