# Generated by Django 5.2.4 on 2025-07-25 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheet', '0005_rename_description_event_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthrough',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='walkthrough',
            name='parent_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cheatsheet.event'),
        ),
    ]
