# Generated by Django 5.2.4 on 2025-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheet', '0006_walkthrough_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthrough',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
