# Generated by Django 5.2.4 on 2025-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheet', '0007_walkthrough_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthrough',
            name='title',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
    ]
