name: Build Static Site to Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        ls
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      run: python nightreigncs/manage.py collectstatic --noinput

    - name: Build static site with django-distill
      run: python nightreigncs/manage.py distill-local --force --output-dir docs

    - name: Fix static/media paths in index.html
      run: |
        sed -i 's|/static/|static/|g' docs/index.html
        sed -i 's|/media/|media/|g' docs/index.html

    - name: Zip the static site
      run: |
        cd docs
        zip -r ../nightreign-cheat-sheet.zip ./*
