name: Build and Deploy Static Site to /docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to commit to main

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      run: python nightreigncs/manage.py collectstatic --noinput

    - name: Build static site
      run: python nightreigncs/manage.py distill-local --force --output-dir docs

    - name: Fix static/media paths in index.html
      run: |
        sed -i 's|/static/|static/|g' docs/index.html
        sed -i 's|/media/|media/|g' docs/index.html
        touch docs/.nojekyll

    - name: Commit and push to main/docs
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/
        git commit -m "Auto-update static site in /docs" || echo "No changes to commit"
        git push
