# Deploy Django-distill static site to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Collect static files
        run: python nightreigncs/manage.py collectstatic --noinput

      - name: Build static site with django-distill
        run: python nightreigncs/manage.py distill-local --force

      - name: Fix paths and disable Jekyll
        run: |
          sed -i 's|/static/|static/|g' nightreign-character-sheet/index.html
          sed -i 's|/media/|media/|g' nightreign-character-sheet/index.html
          touch nightreign-character-sheet/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'nightreign-character-sheet'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
